### ISSUE TITLE
line 126: interproscan.sh: command not found & line 128: interproscan.sh: command not found

### ISSUE THREAD

**Issue by lariver2** [slt666666/NLRtracker#17]
I am having this issue:
Run Interproscan
./NLRtracker.sh: line 126: interproscan.sh: command not found

interproscan.sh -i out_dir/tmp.fasta -f gff3 -t p -o out_dir/interpro_result.gff -cpu 2 -appl Pfam,Gene3D,SUPERFAMILY,PRINTS,SMART,CDD,ProSiteProfiles
./NLRtracker.sh: line 128: interproscan.sh: command not found
WHat would be the solution?

**Comment by slt666666** [comment]
Hi, maybe you didn't install Interproscan.
Please install Interproscan before running NLRtracker.

**Comment by lariver2** [comment]
I ran interproscan alone and it runs very well #beautidully. It seems that I cant get it linked to the NLR Tracker. Any suggestions? Please. Thank you!

**Comment by slt666666** [comment]
"interproscan.sh: command not found"
this error message is caused by your environment.
Please add path to your Interproscan in your environment before running NLRtracker.

**Comment by slt666666** [comment]
"add path" means like this ↓
export PATH="~/XXX(path to your interproscan)/interproscan.sh:$PATH"

**Comment by lariver2** [comment]
I added it and still not working....

**Comment by lariver2** [comment]
Hi There, YEP I add more than 1 PATH and now is working YAY!!!
But I have encountered a new error:
Run NLRtracker
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.0     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.1     ✔ tibble    3.2.0
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Any suggestions, please, please?
Thank you!

**Comment by slt666666** [comment]
Hi, that sounds good!

System has not been booted with systemd as init system (PID 1). Can't operate.
Usually, this ↑ message is caused by WSL system in Windows. So, I can't help to solve it.
Please google this error message, maybe you can find some solutions.

I think R program part in NLRtracker is working.
So, I'm not sure it helps you, but one suggestion from my side is...
1. run the interproscan and fimo before NLRtracker.
like...
- interproscan.sh -i XXX.fasta -appl Pfam,Gene3D,SUPERFAMILY,PRINTS,SMART,CDD,ProSiteProfiles -f gff3
- fimo module/meme.xml XXX.fasta
2. run NLRtracker using `-i` and `-f` options.

**Comment by lariver2** [comment]
Hi there, 
Actually, I do not get any errors after running NLRtarcker.
I got several warnings. But I am pleased with the results. Thank you for your response! You were accommodating.
Best,

**Comment by slt666666** [comment]
OK! Just let me know if you need any help.
Best,
